schedule: "0 3 * * 0"
githubUser: alamont
bucketName: gickup-orikami-nl
mountPath: /gickup-bucket
sshKeySecretName: gickup-ssh-key
githubTokenSecretName: gickup-github-token
gkeProjectId: orikami-kube-a