apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.gkeProjectId }}
    cnrm.cloud.google.com/deletion-policy: abandon
  name: {{ .Values.bucketName }}
spec:
  location: europe-west4
  versioning:
    enabled: true