apiVersion: v1
kind: ConfigMap
metadata:
  name: gickup-configmap
data:
  conf.yml: |
    source:
      github:
        - token_file: /github/token
          user: alamont
          ssh: false
          excludeorgs:
            - alamont
          includeorgs:
            - orikami-nl
    destination:
      local:
        - path: {{ .Values.mountPath }}
          structured: true
          zip: true
          keep: 5
          bare: true
    log:
      file-logging:
        dir: "{{ .Values.mountPath }}/log"
        file: gickup.log