apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: gickup-gsa@{{ .Values.gkeProjectId }}.iam.gserviceaccount.com
  name: gickup-sa
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: gickup-gsa
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.gkeProjectId }}
spec:
  displayName: gickup-gsa
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-workload-identity-gickup-sa
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.gkeProjectId }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: gickup-gsa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{ .Values.gkeProjectId }}.svc.id.goog[github/gickup-sa]
    - role: projects/{{ .Values.gkeProjectId }}/roles/storage
      members:
        - serviceAccount:{{ .Values.gkeProjectId }}.svc.id.goog[github/gickup-sa]